import { createContext, useContext, useState, type ReactNode } from 'react';
import { pt, ptDescription } from './glossary';

export type Lang = 'pt' | 'en';
const dict = {
  pt: {
    appSub: 'Build Planner', buildName: 'Nome da build', author: 'Autor', share: 'Compartilhar link', save: 'Salvar', newBuild: 'Nova', copied: 'Link copiado!', saved: 'Build salva localmente.',
    tabBoard: 'Rune Cast', tabEquip: 'Equipamento', tabRM: 'Mestre de Runas', tabZodiac: 'Zodíaco', zTitle: 'Especializações do Zodíaco', zPts: '{n} nós ativos', zHelp: 'Cada rota tem 4 especializações (Ⅰ, Ⅱ, Ⅲ). Comece pela Lua e siga as linhas; Ⅰ e Ⅱ aceitam até 7 pontos, Ⅲ até 9. Clique para ativar/desativar; passe o mouse para ver o efeito. Dados transcritos das notas oficiais de jan/2025.', zSpec: 'Especialização', zkMoon: 'Nó Lua (entrada)', zkStar: 'Nó Estrela', zkSun: 'Nó Sol', zkCosmos: 'Nó Cosmos', zActive: 'Ativo · clique para remover (remove também os nós dependentes)', zClick: 'Clique para ativar', zCap: 'Limite de {n} pontos nesta especialização', zPrereq: 'Requer o nó anterior da linha', tabItems: 'Itens', tabBuilds: 'Builds salvas', tabDps: 'DPS',
    savedTitle: 'Builds salvas neste navegador', savedEmpty: 'Nenhuma. Use "Salvar" para guardar a build atual; use "Compartilhar link" para enviá-la à comunidade.', open: 'Abrir', del: 'Excluir', cells: 'células',
    notes: 'Notas', notesPh: 'Descrição, ordem de prioridade, dicas…',
    footer: 'Dados: {runes} runas · {runestones} runestones · {uniques} únicos · {rm} nós do Mestre de Runas · {zod} nós do Zodíaco · {auth} autoridades — fonte', footer2: 'e guia oficial. Projeto de fãs, não afiliado à LINE Games.',
    boardHint: 'clique: runa · clique direito: runestone · runas de gatilho: ↻ gira a seta (alvo na seta, ativação no lado oposto)', runeLevel: 'Nível da runa', runeLevelTip: 'Cap base 45; Rune Candor Essence: +1 a cada 5 sucessos, máx. +5', bonus: 'bônus', bonusTip: '+X Skill Rune Level de equipamentos / Improved Technique',
    noLinks: 'Nenhuma link rune adjacente.', orphans: 'Link runes sem skill adjacente:', boardEmpty: 'Adicione skill runes ao tabuleiro. Link runes nos 6 hexágonos vizinhos são vinculadas à skill.',
    pickRune: 'Selecionar runa', pickStone: 'Selecionar runestone', type: 'Tipo', tag: 'Tag', rarity: 'Raridade', all: 'todos', search: 'Buscar…', remove: 'Remover', nothing: 'Nada encontrado.', skillRune: 'Skill Rune', linkRune: 'Link Rune',
    tabGallery: 'Galeria', galleryTitle: 'Galeria da comunidade', galleryHint: 'builds publicadas como issues no GitHub', publish: 'Publicar build atual', allStats: 'Todos os atributos', loading: 'Carregando…', galleryErr: 'Não foi possível carregar a galeria', galleryEmpty: 'Nenhuma build publicada ainda. Seja o primeiro!', galleryFoot: 'Publicar abre uma issue pré-preenchida no GitHub (precisa de conta GitHub). Curta com 👍 e comente na própria issue. Fonte:',
    tabCompare: 'Comparar', cmpTitle: 'Comparar builds', cmpHint: 'A = build atual; escolha B de uma build salva ou cole um link/código', cmpPickSaved: 'Build salva…', cmpPaste: 'Cole um link ou código de build', cmpLoad: 'Carregar', cmpBad: 'Código inválido', cmpEmpty: 'Selecione ou cole a build B para comparar.', cmpStat: 'Atributo', cmpSkills: 'Skills', cmpLinks: 'Link runes', cmpRm: 'Pontos de Mestre de Runas', cmpDiffOnly: 'somente diferenças', cmpSame: 'Idênticos.',
    searchTitle: 'Busca global (Ctrl+K)', shareView: 'Link somente leitura', shareViewTip: 'Copia um link que abre a build em modo de visualização (sem edição)', editBuild: 'Editar esta build', by: 'por', theme: 'Tema claro/escuro',
    exported: 'Imagem exportada', exportTip: 'Exportar card da build (PNG 1200×675) para Discord/redes',
    presetsTitle: 'Builds prontas', presetsHint: 'builds da comunidade por temporada + modelos iniciais — abra, ajuste as cores dos slots e evolua', stageStart: 'Campanha', stageEnd: 'Endgame', slotsReq: 'Cores de slot necessárias na skill principal (role com Rune Color Essence)', dpsPerHit: 'dano/hit estimado (arma 300)', presetsDisclaimer: 'Builds da comunidade são reconstruídas a partir de guias públicos (vídeos/documentos dos criadores). Onde o guia não lista todas as runas de link, as restantes foram inferidas pelas tags do jogo — confira a fonte.', shortcuts: 'Atalhos: 1–9 abas · Ctrl+Z/Y desfazer/refazer · Ctrl+S salvar · Ctrl+K buscar',
    authTitle: 'Autoridade dos Deuses',
    charTitle: 'Personagem', charHint: 'usado para checar requisitos de únicos e do Mestre de Runas', char_level: 'Nível', char_str: 'FOR', char_dex: 'DES', char_int: 'INT', checkOk: 'Nenhum problema de requisito encontrado.',
    reqLevel: '{item} ({slot}) exige nível {n}', reqStat: '{item} ({slot}) exige {stat} {n}', rmLevel: 'Nó {node} desbloqueia só no nível {n}', authDup: 'Autoridade de {god} repetida em {a} e {b} (o jogo só ativa uma por deus)',
    grade: 'Grau da runa (N/M/R/L)', awaken: 'Despertar (Source/Origin/Verity)',
    helpTitle: 'Como funcionam os slots e essências',
    help1: 'Cada Skill Rune tem até 6 slots de vínculo (um por lado do hexágono). Essência de Nascimento (Rune Birth) abre 1–6 slots; a Hexa Rune Essence abre os 6 garantido.',
    help2: 'Cada slot aberto tem uma cor: Vermelho, Verde ou Azul. A Link Rune só faz efeito se a cor dela combinar com a do slot e se as tags baterem com a skill. Essência de Cor (Rune Color) sorteia a cor; Essência de Vínculo (Rune Link) muda a posição sem mudar a cor.',
    help3: 'Rune Candor Essence transforma um slot em Branco: aceita Link Rune de qualquer cor e dá +1 nível à Link Rune vinculada por acúmulo.',
    help4: 'A cada 5 Candor bem-sucedidos o nível máximo da Skill Rune sobe +1 (até +5, ou seja, 50). Acima do máximo, itens “Rune Growth” elevam o nível.',
    help5: 'Runas Vermelhas costumam ser Físicas/Corpo a Corpo (STR), Verdes Projétil/Alcance (DEX) e Azuis Magia/Elementais (INT).',
    help6: 'No planner: clique nos pontos ao redor da skill para ciclar a cor do slot (indefinido → R → G → B → Branco → fechado). Slot indefinido não é validado. O botão N/M/R/L define o grau da runa e ☆ escolhe o Despertar (Source/Origin/Verity).',
    helpSrc: 'Fonte: guia oficial de Encantamento de Runas —',
    slotClosed: 'Slot de vínculo fechado (use Essência de Nascimento)', slotColor: 'Cor do slot não combina: {tags}', slots: 'Slots', slotHint: 'clique nos pontos ao redor da skill para definir a cor de cada slot (Vermelho/Verde/Azul/Branco/fechado)', autoSlots: 'Ajustar slots às link runes', rollTodo: 'A rolar', rollDone: 'slots prontos para os links atuais', rollOpen: 'slot {n}: abrir (Essência de Nascimento)', rollColor: 'slot {n}: rolar para {c} (Essência de Cor)', rollUnset: 'slot {n}: precisa ser {c}', color: 'Cor',
    rotate: 'Girar seta da runa de gatilho', trigTarget: 'Alvo (na direção da seta)', trigActivation: 'Ativação (lado oposto)', trigMismatch: 'skill não tem as tags exigidas', trigNone: 'nenhuma skill nesse hexágono',
    linkNoTags: 'Link rune sem tags restritivas — aplica-se a qualquer skill.', linkVia: 'Compatível via {tags}', linkMissing: 'Skill não possui nenhuma das tags: {tags}',
    equipTitle: 'Equipamento & Autoridade dos Deuses', equipHint: 'clique: item único · clique direito: autoridade', equipEmpty: 'Nenhum item equipado. Clique num slot para escolher um item único (707 disponíveis) ou clique direito para definir a Autoridade dos Deuses do slot.', item: 'Item', authority: 'Autoridade', uniquePick: 'Único — {slot}', authPick: 'Autoridade — {slot}',
    slot_Helmet: 'Elmo', slot_Necklace: 'Colar', slot_Pauldrons: 'Ombreiras', slot_Armor: 'Armadura', slot_Weapons: 'Arma', slot_Offhand: 'Mão secundária', slot_Gloves: 'Luvas', slot_Belt: 'Cinto', slot_Ring1: 'Anel', slot_Ring2: 'Anel', slot_Shoes: 'Botas',
    rmTitle: 'Caminho do Mestre de Runas', rmPts: '{n} pontos distribuídos', rmAll: 'Todas as constelações', reset: 'Resetar', rmHint: 'Clique para adicionar ponto · clique direito para remover · tiers exigem pontos no tier anterior.', rmUnlock: 'Desbloqueia no nível {lv} · máx. {max} pontos', rmReq: 'requer {n} pontos no Tier {t}', rmMissing: 'faltam {n}', perPoint: '[por ponto]', points: 'pontos',
    itemsTitle: 'Itens', essences: 'Essências', potions: 'Poções', coins: 'Moedas', materials: 'Materiais', itemsEmpty: 'Sem dados ainda — a carga do banco preenche esta seção.',
    tipMissing: 'Detalhes ainda não importados', patchNotes: 'Notas de atualização', tipPlaceholderIcon: 'ícone provisório', tipUnofficial: 'Runa nova: números não publicados nas notas oficiais — tags/descrição inferidas; sem cálculo de DPS.', tipEst: 'Interpolado entre Lv1 e Lv45 do banco', weapon: 'Arma', source: 'Fonte', unlockAt: 'Desbloqueia',
    dpsTitle: 'Estimativa de dano', dpsHint: 'Estimativa simplificada a partir dos stats do banco (nível selecionado) e dos modificadores dos link runes / Mestre de Runas / Zodíaco (nós condicionais a arma só contam com a arma correspondente equipada). Não substitui o cálculo do jogo.', dpsSkill: 'Skill', dpsBase: 'DMG base da runa', dpsFlat: 'DMG fixo', dpsMore: 'Multiplicadores (link runes)', dpsInc: 'Aumentos (%)', dpsAmp: 'Amplificação (%)', dpsResult: 'DMG por uso (estimado)', dpsCost: 'Custo de mana', dpsNoSkill: 'Coloque uma skill rune no tabuleiro para ver a estimativa.',
    weaponDmg: 'DMG da arma (média)', charStat: 'Bônus do personagem (%)', origText: 'Texto original (EN)', origTip: 'Mostrar stats e regras no inglês original em vez do glossário PT',
  },
  en: {
    appSub: 'Build Planner', buildName: 'Build name', author: 'Author', share: 'Share link', save: 'Save', newBuild: 'New', copied: 'Link copied!', saved: 'Build saved locally.',
    tabBoard: 'Rune Cast', tabEquip: 'Equipment', tabRM: 'Rune Master', tabZodiac: 'Zodiac', zTitle: 'Zodiac Specializations', zPts: '{n} nodes active', zHelp: 'Each route has 4 specializations (Ⅰ, Ⅱ, Ⅲ). Start at the Moon and follow the lines; Ⅰ and Ⅱ take up to 7 points, Ⅲ up to 9. Click to toggle; hover for the effect. Data transcribed from the official Jan 2025 notes.', zSpec: 'Specialization', zkMoon: 'Moon node (entry)', zkStar: 'Star node', zkSun: 'Sun node', zkCosmos: 'Cosmos node', zActive: 'Active · click to remove (also removes dependent nodes)', zClick: 'Click to activate', zCap: 'Limit of {n} points in this specialization', zPrereq: 'Requires the previous node on the line', tabItems: 'Items', tabBuilds: 'Saved builds', tabDps: 'DPS',
    savedTitle: 'Builds saved in this browser', savedEmpty: 'None yet. Use "Save" to keep the current build; use "Share link" to send it to the community.', open: 'Open', del: 'Delete', cells: 'cells',
    notes: 'Notes', notesPh: 'Description, priority order, tips…',
    footer: 'Data: {runes} runes · {runestones} runestones · {uniques} uniques · {rm} Rune Master nodes · {zod} Zodiac nodes · {auth} authorities — source', footer2: 'and the official guide. Fan project, not affiliated with LINE Games.',
    boardHint: 'click: rune · right-click: runestone · trigger runes: ↻ rotates the arrow (target in arrow direction, activation opposite)', runeLevel: 'Rune level', runeLevelTip: 'Base cap 45; Rune Candor Essence: +1 per 5 successes, max +5', bonus: 'bonus', bonusTip: '+X Skill Rune Level from gear / Improved Technique',
    noLinks: 'No adjacent link rune.', orphans: 'Link runes without adjacent skill:', boardEmpty: 'Add skill runes to the board. Link runes in the 6 neighbouring hexes are linked to the skill.',
    pickRune: 'Select rune', pickStone: 'Select runestone', type: 'Type', tag: 'Tag', rarity: 'Rarity', all: 'all', search: 'Search…', remove: 'Remove', nothing: 'Nothing found.', skillRune: 'Skill Rune', linkRune: 'Link Rune',
    tabGallery: 'Gallery', galleryTitle: 'Community gallery', galleryHint: 'builds published as GitHub issues', publish: 'Publish current build', allStats: 'All stats', loading: 'Loading…', galleryErr: 'Could not load the gallery', galleryEmpty: 'No builds published yet. Be the first!', galleryFoot: 'Publishing opens a pre-filled GitHub issue (GitHub account required). Upvote with 👍 and discuss in the issue. Source:',
    tabCompare: 'Compare', cmpTitle: 'Compare builds', cmpHint: 'A = current build; pick B from a saved build or paste a link/code', cmpPickSaved: 'Saved build…', cmpPaste: 'Paste a build link or code', cmpLoad: 'Load', cmpBad: 'Invalid code', cmpEmpty: 'Select or paste build B to compare.', cmpStat: 'Stat', cmpSkills: 'Skills', cmpLinks: 'Link runes', cmpRm: 'Rune Master points', cmpDiffOnly: 'differences only', cmpSame: 'Identical.',
    searchTitle: 'Global search (Ctrl+K)', shareView: 'Read-only link', shareViewTip: 'Copies a link that opens the build in view mode (no editing)', editBuild: 'Edit this build', by: 'by', theme: 'Light/dark theme',
    exported: 'Image exported', exportTip: 'Export build card (PNG 1200×675) for Discord/social',
    presetsTitle: 'Ready builds', presetsHint: 'community builds by season + starter templates — open, adjust slot colours and grow', stageStart: 'Campaign', stageEnd: 'Endgame', slotsReq: 'Slot colours needed on the main skill (roll with Rune Color Essence)', dpsPerHit: 'est. dmg/hit (weapon 300)', presetsDisclaimer: 'Community builds are rebuilt from public guides (creators\' videos/documents). Where a guide does not list every link rune, the rest were inferred from in-game tags — check the source.', shortcuts: 'Shortcuts: 1–9 tabs · Ctrl+Z/Y undo/redo · Ctrl+S save · Ctrl+K search',
    authTitle: 'Authority of the Gods',
    charTitle: 'Character', charHint: 'used to check unique and Rune Master requirements', char_level: 'Level', char_str: 'STR', char_dex: 'DEX', char_int: 'INT', checkOk: 'No requirement issues found.',
    reqLevel: '{item} ({slot}) requires level {n}', reqStat: '{item} ({slot}) requires {stat} {n}', rmLevel: 'Node {node} unlocks at level {n}', authDup: 'Authority of {god} duplicated in {a} and {b} (only one per god is active)',
    grade: 'Rune grade (N/M/R/L)', awaken: 'Awakening (Source/Origin/Verity)',
    helpTitle: 'How link slots and essences work',
    help1: 'Each Skill Rune has up to 6 link slots (one per hex side). Rune Birth Essence opens 1–6 slots by chance; a Hexa Rune Essence opens all 6 guaranteed.',
    help2: 'Every open slot has a colour: Red, Green or Blue. A Link Rune only takes effect when its colour matches the slot and its tags match the skill. Rune Color Essence rerolls colours; Rune Link Essence moves slots without changing colours.',
    help3: 'Rune Candor Essence turns a slot White: it accepts any Link Rune colour and grants +1 level to the linked Link Rune per stack.',
    help4: 'Every 5 successful Candor enchants raise the Skill Rune max level by +1 (up to +5, i.e. 50). Beyond that, “Rune Growth” elements raise the level.',
    help5: 'Red runes are mostly Physical/Melee (STR), Green Projectile/Ranged (DEX), Blue Spell/Elemental (INT).',
    help6: 'In the planner: click the dots around a skill to cycle the slot colour (unset → R → G → B → White → closed). Unset slots are not validated. The N/M/R/L button sets the rune grade and ☆ picks the Awakening (Source/Origin/Verity).',
    helpSrc: 'Source: official Rune Enchant guide —',
    slotClosed: 'Link slot closed (use a Rune Birth Essence)', slotColor: 'Slot colour mismatch: {tags}', slots: 'Slots', slotHint: 'click the dots around a skill to set each link slot colour (Red/Green/Blue/White/closed)', autoSlots: 'Match slots to link runes', rollTodo: 'To roll', rollDone: 'slots ready for the current links', rollOpen: 'slot {n}: open (Birth Essence)', rollColor: 'slot {n}: roll to {c} (Colour Essence)', rollUnset: 'slot {n}: must be {c}', color: 'Colour',
    rotate: 'Rotate trigger rune arrow', trigTarget: 'Target (arrow direction)', trigActivation: 'Activation (opposite side)', trigMismatch: 'skill lacks the required tags', trigNone: 'no skill in that hex',
    linkNoTags: 'Link rune without restrictive tags — applies to any skill.', linkVia: 'Compatible via {tags}', linkMissing: 'Skill has none of the tags: {tags}',
    equipTitle: 'Equipment & Authority of the Gods', equipHint: 'click: unique item · right-click: authority', equipEmpty: 'Nothing equipped. Click a slot to choose a unique item (707 available) or right-click to set the slot\'s Authority of the Gods.', item: 'Item', authority: 'Authority', uniquePick: 'Unique — {slot}', authPick: 'Authority — {slot}',
    slot_Helmet: 'Helmet', slot_Necklace: 'Necklace', slot_Pauldrons: 'Pauldrons', slot_Armor: 'Armor', slot_Weapons: 'Weapon', slot_Offhand: 'Off-hand', slot_Gloves: 'Gloves', slot_Belt: 'Belt', slot_Ring1: 'Ring', slot_Ring2: 'Ring', slot_Shoes: 'Shoes',
    rmTitle: 'Path of the Rune Master', rmPts: '{n} points allocated', rmAll: 'All constellations', reset: 'Reset', rmHint: 'Click to add a point · right-click to remove · tiers require points in the previous tier.', rmUnlock: 'Unlocks at level {lv} · max {max} points', rmReq: 'requires {n} points in Tier {t}', rmMissing: '{n} missing', perPoint: '[per point]', points: 'points',
    itemsTitle: 'Items', essences: 'Essences', potions: 'Potions', coins: 'Coins', materials: 'Materials', itemsEmpty: 'No data yet — the database refresh fills this section.',
    tipMissing: 'Details not imported yet', patchNotes: 'Patch notes', tipPlaceholderIcon: 'placeholder icon', tipUnofficial: 'New rune: numbers not published in the official notes — tags/description inferred; no DPS estimate.', tipEst: 'Interpolated between Lv1 and Lv45 from the database', weapon: 'Weapon', source: 'Source', unlockAt: 'Unlocks',
    dpsTitle: 'Damage estimate', dpsHint: 'Simplified estimate from the database stats (selected level) plus link rune / Rune Master / Zodiac modifiers (weapon-conditional nodes only count with a matching weapon equipped). Not a replacement for the in-game calculation.', dpsSkill: 'Skill', dpsBase: 'Rune base DMG', dpsFlat: 'Flat DMG', dpsMore: 'Multipliers (link runes)', dpsInc: 'Increases (%)', dpsAmp: 'Amplification (%)', dpsResult: 'DMG per use (estimated)', dpsCost: 'Mana cost', dpsNoSkill: 'Place a skill rune on the board to see the estimate.',
    weaponDmg: 'Weapon DMG (average)', charStat: 'Character bonus (%)', origText: 'Original text (EN)', origTip: 'Show stats and rules in original English instead of the PT glossary',
  },
} as const;
export type Key = keyof typeof dict.pt;

const Ctx = createContext<{ lang: Lang; setLang: (l: Lang) => void; t: (k: Key, vars?: Record<string, string | number>) => string; g: (line: string) => string; gd: (slug: string, text: string) => string; showOriginal: boolean; setShowOriginal: (v: boolean) => void }>(null!);
export function I18nProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => (localStorage.getItem('lang') as Lang) || (navigator.language.startsWith('pt') ? 'pt' : 'en'));
  const setLang = (l: Lang) => { localStorage.setItem('lang', l); setLangState(l); document.documentElement.lang = l === 'pt' ? 'pt-BR' : 'en'; };
  const t = (k: Key, vars: Record<string, string | number> = {}) => (dict[lang][k] as string).replace(/\{(\w+)\}/g, (_, v) => String(vars[v] ?? ''));
  const [showOriginal, setShowOriginalState] = useState(localStorage.getItem('showOriginal') === '1');
  const setShowOriginal = (v: boolean) => { localStorage.setItem('showOriginal', v ? '1' : '0'); setShowOriginalState(v); };
  /** Game-text translator: PT glossary when lang is pt (unless the user asked for original text). */
  const gd = (slug: string, text: string) => (lang === 'pt' && !showOriginal ? ptDescription(slug, text) : text);
  const g = (line: string) => (lang === 'pt' && !showOriginal ? pt(line) : line);
  return <Ctx.Provider value={{ lang, setLang, t, g, gd, showOriginal, setShowOriginal }}>{children}</Ctx.Provider>;
}
export const useT = () => useContext(Ctx);
